version: "3.7"
services:
    goodreads-notebook:
        container_name: goodreads-notebook
        image: local/jupyter_nb_base:latest
        volumes:
            - "./goodreads_nb/notebook:/notebook"
        ports:
            - "8001:8888"
    data-scrape-notebook:
        container_name: data-scrape-notebook
        build:
            context: .
            dockerfile: ./data_scrape_nb/Dockerfile
        volumes:
            - "./data_scrape_nb/notebook:/notebook"
        ports:
            - "8002:8888"
    randomized-optimization-8-queens-notebook:
        container_name: randomized-optimization-8-queens-notebook
        build:
            context: .
            dockerfile: ./randomized_optimization_8_queens_nb/Dockerfile
        volumes:
            - "./randomized_optimization_8_queens_nb/notebook:/notebook"
        ports:
            - "8003:8888"
    tf-linear-regression-notebook:
        container_name: tf-linear-regression-notebook
        build:
            context: .
            dockerfile: ./tf_linear_regression_nb/Dockerfile
        volumes:
            - "./tf_linear_regression_nb/notebook:/notebook"
        ports:
            - "8004:8888"
    mnist-handwritten-notebook:
        container_name: mnist-handwritten-notebook
        build:
            context: .
            dockerfile: ./mnist_handwritten_nb/Dockerfile
        volumes:
            - "./mnist_handwritten_nb/notebook:/notebook"
        ports:
            - "8005:8888"

