version: "3.7"
services:
    goodreads-notebook:
        container_name: goodreads-notebook
        build:
            context: .
            dockerfile: ./notebooks/goodreads/Dockerfile
        image: goodreads-notebook:latest
        volumes:
            - "./notebooks/goodreads:/notebook"
        ports:
            - "8001:8888"
    data-scrape-notebook:
        container_name: data-scrape-notebook
        build:
            context: .
            dockerfile: ./notebooks/data_scrape/Dockerfile
        image: data-scrape-notebook:latest
        volumes:
            - "./notebooks/data_scrape:/notebook"
        ports:
            - "8002:8888"
